version: "2"

services:
  minecraft:
    build:
      context: .
    container_name: "minecraft"
    image: minecraft
    restart: on-failure
    ports:
      - "25565:25565"
      - "8123:8123"
      - "27075:27075"
    volumes:
      - .:/minecraft
