version: "3"

services:
  minecraft:
    build:
      context: .
    container_name: "minecraft"
    image: minecraft
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "25565:25565"
      - "8123:8123"
      - "27075:27075"
    volumes:
      - .:/minecraft
