version: "3.4"

services:
  ark:
    container_name: ark
    image: boerngenschmidt/ark-docker
    environment:
      - SESSIONNAME=Nebtown
      - SERVERMAP=${SERVERMAP:-TheIsland}
      - SAVEDIRECTORY=${SAVEDIRECTORY:-SavedArks}
      - MAX_PLAYERS=12
      - SERVERPASSWORD=
      - ADMINPASSWORD=${ADMINPASSWORD:-}
      - SERVERPORT=27015
      - STEAMPORT=7778
      - BACKUPONSTART=1
      - BACKUPONSTOP=1
      - WARNONSTOP=1
      - UPDATEONSTART=${UPDATEONSTART:-1}
      - TZ=UTC
      - ARK_GID=1000
      - ARK_UID=1000
    volumes:
      - ./volume:/ark
      - ./Saved:/ark/server/ShooterGame/Saved
    ports:
      - 7778:7778/udp
      - 7778:7778
      - 27015:27015/udp
      - 27015:27015
      - 32330:32330
