version: '3.4'
services:
  tf2:
    image: cm2network/tf2
    container_name: tf2
    tty: true
    stdin_open: true
    restart: on-failure
    ports:
      - "27062:27062/udp" # game
      - "27062:27062/tcp" # rcon
    volumes:
      - ./mount:/home/steam/tf-dedicated
    environment:
      - SRCDS_TOKEN=${SRCDS_TOKEN}
      - SRCDS_MAXPLAYERS=${SRCDS_MAXPLAYERS:-24}
      - SRCDS_HOSTNAME=${SRCDS_HOSTNAME:-Nebtown Orange}
      - SRCDS_STARTMAP=${SRCDS_STARTMAP:-cp_orange_x_7_fm}
      - SRCDS_PW=${SRCDS_PW:-}
      - SRCDS_PORT=${SRCDS_PORT:-27062}
      - SRCDS_NET_PUBLIC_ADDRESS=${SRCDS_NET_PUBLIC_ADDRESS}
      - SRCDS_REGION=${SRCDS_REGION:-1}
